(SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
        PRODUCT_ID,
        USER_ID,
        SALES_AMOUNT
 
    FROM ONLINE_SALE
    WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03')

UNION ALL

(SELECT DATE_FORMAT(sales_date, '%Y-%m-%d') AS SALES_DATE,
        PRODUCT_ID, 
        CASE WHEN OFFLINE_SALE_ID IS NOT NULL THEN NULL
        END AS USER_ID, 
        SALES_AMOUNT
 
    FROM OFFLINE_SALE
    WHERE DATE_FORMAT(sales_date, '%Y-%m') = '2022-03')
    
ORDER BY 1, 2, 3