SELECT a.CATEGORY, SUM(b.SALES)
    FROM BOOK a
    JOIN BOOK_SALES b ON a.BOOK_ID = b.BOOK_ID
    WHERE EXTRACT(YEAR_MONTH FROM b.SALES_DATE) = '202201'
    GROUP BY a.CATEGORY
    ORDER BY a.CATEGORY