SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
    FROM APPOINTMENT A
        JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
        JOIN PATIENT P ON A.PT_NO = P.PT_NO
    WHERE A.APNT_CNCL_YN = 'N'
        AND EXTRACT(YEAR_MONTH FROM A.APNT_YMD) = '202204'
        AND DAY(A.APNT_YMD) = '13'
        AND A.MCDP_CD = 'CS'
    ORDER BY 6